name: Docker Image build/push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login 
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_ACCESS_KEY}}
    - name: Build the Docker image
      run: docker build -t kokadva/kafka-kraft-kube:3.3.1 -f kubernetes/Dockerfile kubernetes/
    - name: Push the Docker image
      run: docker push kokadva/kafka-kraft-kube:3.3.1
      
