name: Docker Image build/push

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docker/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'docker/**'

jobs:

  build_deploy_docker_image:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_ACCESS_KEY}}
      - name: Build the Docker image
        run: docker build -t kokadva/kafka-kraft -f docker/Dockerfile docker/
      - name: Push the Docker image
        run: docker push kokadva/kafka-kraft
